version: "3.7"

services:
    master:
        build:
            context: master
            dockerfile: Dockerfile
        volumes:
          - ./master/salt:/etc/salt
            
    minion:
        build:
           context: minion
           dockerfile: Dockerfile
        links:
           - "master:salt"
